### ISSUE TITLE
`macroWeighted` is superfluous

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/openPMD-standard#124]
Argh, `macroWeighted` is superfluous and can be removed, e.g., with the following definition of `weightingPower` in the future:
- macro particle attribute == real particle attribute: `weightingPower` == `0`
- attribute is stored `for macro particle` and can be _linearly_ scaled to real particle: `weightingPower` == `-1.0`
- attribute is stored `for real particle` and can be _linearly_ scaled to macro particle: `weightingPower` == `1.0`

(thx @psychocoderHPC, I must have been blind; currently `weightingPower` is always positive)

**Comment by ax3l** [comment]
well, actually there might be particle records that are inversely scaling with weighting.

let us define `m^-1` as a record called "mobility" (inverse inertness). The "mobility" scales with `w**-1` for a macro particle. We can **not** determine _by the sign_ of `weightingPower` if the currently stored record describes a _macro particle_ or a _real particle_ without checking `macroWeighted`.

**Comment by RemiLehe** [comment]
Yes, I agree with your last comments. It seems that `macroWeighted` is still useful. Should we close the issue?

**Comment by ax3l** [comment]
Yes, let's close it :)
