### ISSUE TITLE
`axisLabels` with better example

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/openPMD-standard#130]
Backwards compatible enhancement (before #129 can be implemented, which would break backwards compatibility).

The writing in `axisLabels` (and `gridSpacing`, etc.) should be as with the _bracket indexing method_ that _wrote_ the record.

E.g., a C-style `E[z,y,x]` with `dataOrder='C'` would be `axisLabels="z;y;x"` (PIConGPU). Warp uses C-style indexing `E[x,y,z]` with `dataOrder='C'` which would be `axisLabels="x;y;z".

A Fortran code `E[x,y,z]` with `dataOrder='F'` would write `axisLabels="x;y;z"`.

**Comment by jaysgstop** [comment]
In pressing charges
