### ISSUE TITLE
unitSI for dimensionless record components

### ISSUE THREAD

**Issue by DavidSagan** [ComputationalRadiationPhysics/openPMD-standard#147]
For the documentation for unitSI there is

> Rationale: can also be used to scale a dimension-less component.

I understand the words but I cannot think of where this could be of use. Can someone give me an example?

(Migrated from https://github.com/marcguetg/h5particle/issues/13)

**Comment by DavidSagan** [comment]
Answer from @ax3l:

>The short answer: a dimensionless-unit can still be scaled, e.g. to a typical particle weighting of all macro particles of a simulation. It could also be anything else, e.g. a detector count that is in quantities of kilo-events per pixel, a RGB value that is 0.0:1.0 but shall be scaled to 0:255 or 0:65535, ....
The fundamental idea is: whatever heavy user data a user's sim/detector/instrument/... provides, we do not enforce to convert it before writes.

**Comment by ax3l** [comment]
I will close the issue for now, if there are no further questions to it. Otherwise we can re-open it anytime :)
