### ISSUE TITLE
Use "group" instead of "directory"

### ISSUE THREAD

**Issue by DavidSagan** [ComputationalRadiationPhysics/openPMD-standard#160]
In the standard "group" and "directory" are used interchangeably. It would make things clearer if only one or the other was used and "group" makes more sense than "directory".

@ax3l: Please put this in the project 1.1 queue.

**Comment by ax3l** [comment]
Thanks for the report!

Actually, only used to refer to `/`. The term "directory" is currently used three times in exactly that formulation:

> *root* directory (path `/`)

when referring to `/`.

I agree that we can also call this immediately 

> *root* group (path `/`)

.

**Comment by ax3l** [comment]
implemented
