### ISSUE TITLE
Standardizing Particle Species Name

### ISSUE THREAD

**Issue by DavidSagan** [ComputationalRadiationPhysics/openPMD-standard#176]
Standardizing the particle species names will make data files more portable.
I am submitting a pull request with a proposed list of names.

**Comment by DavidSagan** [comment]
@RemiLehe @ax3l: OK a pull request has been submitted.

**Comment by ax3l** [comment]
Offline results from the last VC: the new extension should define an `attribute` that can be put both on mesh and particle records to describe the species type (via it's value), independent of the record name.

The extension should therefore define a new reserved `record` attribute and allowed `values` for it.

**Comment by DavidSagan** [comment]
@ax3l: OK how about `SpeciesName` or `SpeciesType` for the attribute name?

**Comment by ax3l** [comment]
sounds good :)

**Comment by ax3l** [comment]
or `PhysicalSpecies`?
