### ISSUE TITLE
Are text attributes case-sensitive?

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/openPMD-standard#227]
Question occured because of `currentSmoothing` possible values containing weirdly capitalized `Binomial`, even though generally it feels the non-capitalized names are used.

**Comment by DavidSagan** [comment]
Yes case sensitive.

**Comment by sbastrakov** [comment]
Thanks @DavidSagan !

So now I know capitalized `Binomial` current smoothing is correct (even tho not sure it is logical).
