### ISSUE TITLE
Bool -> UInt

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/openPMD-standard#26]
Use integers instead of Boolean values (same size).

some standards, such as HDF5, do not have a native bool type and using the [h5py](http://docs.h5py.org/en/latest/faq.html)/[libSplash](https://github.com/ComputationalRadiationPhysics/libSplash/issues/152) _enum work-around_ is [not standardized](http://www.hdfgroup.org/hdf5-quest.html#bool).

**Comment by DavidSagan** [comment]
Need this for the Beam Physics extension. Propose: 0 = False, everything else is True.

**Comment by ax3l** [comment]
Yes, it's probably easiest to stay with integers as used in `C` there.
